# https://gohugo.io/hosting-and-deployment/hosting-on-github/

name: Build and deploy GitHub pages

on:
  push:
    paths:
      - 'docs/**'
      - '.github/workflows/gh-pages.yml'
    branches:
      - main  # Set a branch to deploy
  pull_request:

  # Enable manual workflow triggering from the Actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

env:
  # Set the documentation root
  documentation_root: './docs'

jobs:
  build:
    permissions:
      contents: read
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ${{ env.documentation_root }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Install dependencies
        run: npm ci

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 0.123.8
          extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ env.documentation_root }}/public